export const timezones = [
    { value: "Africa/Algiers", label: "Africa/Algiers" },
    { value: "Africa/Cairo", label: "Africa/Cairo" },
    { value: "Africa/Casablanca", label: "Africa/Casablanca" },
    { value: "Africa/Harare", label: "Africa/Harare" },
    { value: "Africa/Lagos", label: "Africa/Lagos" },
    { value: "Africa/Nairobi", label: "Africa/Nairobi" },
    { value: "America/Argentina/Buenos_Aires", label: "America/Argentina/Buenos_Aires" },
    { value: "America/Asuncion", label: "America/Asuncion" },
    { value: "America/Bahia_Banderas", label: "America/Bahia_Banderas" },
    { value: "America/Belize", label: "America/Belize" },
    { value: "America/Bogota", label: "America/Bogota" },
    { value: "America/Boise", label: "America/Boise" },
    { value: "America/Caracas", label: "America/Caracas" },
    { value: "America/Chicago", label: "America/Chicago" },
    { value: "America/Chihuahua", label: "America/Chihuahua" },
    { value: "America/Dawson", label: "America/Dawson" },
    { value: "America/Denver", label: "America/Denver" },
    { value: "America/Detroit", label: "America/Detroit" },
    { value: "America/Edmonton", label: "America/Edmonton" },
    { value: "America/Glace_Bay", label: "America/Glace_Bay" },
    { value: "America/Godthab", label: "America/Godthab" },
    { value: "America/Guatemala", label: "America/Guatemala" },
    { value: "America/Indiana/Indianapolis", label: "America/Indiana/Indianapolis" },
    { value: "America/Juneau", label: "America/Juneau" },
    { value: "America/Los_Angeles", label: "America/Los_Angeles" },
    { value: "America/Louisville", label: "America/Louisville" },
    { value: "America/Managua", label: "America/Managua" },
    { value: "America/Manaus", label: "America/Manaus" },
    { value: "America/Mexico_City", label: "America/Mexico_City" },
    { value: "America/Montevideo", label: "America/Montevideo" },
    { value: "America/New_York", label: "America/New_York" },
    { value: "America/Noronha", label: "America/Noronha" },
    { value: "America/Phoenix", label: "America/Phoenix" },
    { value: "America/Regina", label: "America/Regina" },
    { value: "America/Santiago", label: "America/Santiago" },
    { value: "America/Santo_Domingo", label: "America/Santo_Domingo" },
    { value: "America/Sao_Paulo", label: "America/Sao_Paulo" },
    { value: "America/St_Johns", label: "America/St_Johns" },
    { value: "America/Tijuana", label: "America/Tijuana" },
    { value: "America/Toronto", label: "America/Toronto" },
    { value: "Asia/Almaty", label: "Asia/Almaty" },
    { value: "Asia/Amman", label: "Asia/Amman" },
    { value: "Asia/Baghdad", label: "Asia/Baghdad" },
    { value: "Asia/Baku", label: "Asia/Baku" },
    { value: "Asia/Bangkok", label: "Asia/Bangkok" },
    { value: "Asia/Colombo", label: "Asia/Colombo" },
    { value: "Asia/Dhaka", label: "Asia/Dhaka" },
    { value: "Asia/Dubai", label: "Asia/Dubai" },
    { value: "Asia/Irkutsk", label: "Asia/Irkutsk" },
    { value: "Asia/Jerusalem", label: "Asia/Jerusalem" },
    { value: "Asia/Kabul", label: "Asia/Kabul" },
    { value: "Asia/Karachi", label: "Asia/Karachi" },
    { value: "Asia/Kathmandu", label: "Asia/Kathmandu" },
    { value: "Asia/Kolkata", label: "Asia/Kolkata" },
    { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk" },
    { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur" },
    { value: "Asia/Kuwait", label: "Asia/Kuwait" },
    { value: "Asia/Magadan", label: "Asia/Magadan" },
    { value: "Asia/Qatar", label: "Asia/Qatar" },
    { value: "Asia/Rangoon", label: "Asia/Rangoon" },
    { value: "Asia/Seoul", label: "Asia/Seoul" },
    { value: "Asia/Shanghai", label: "Asia/Shanghai" },
    { value: "Asia/Taipei", label: "Asia/Taipei" },
    { value: "Asia/Tehran", label: "Asia/Tehran" },
    { value: "Asia/Tokyo", label: "Asia/Tokyo" },
    { value: "Asia/Vladivostok", label: "Asia/Vladivostok" },
    { value: "Asia/Yakutsk", label: "Asia/Yakutsk" },
    { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg" },
    { value: "Atlantic/Azores", label: "Atlantic/Azores" },
    { value: "Atlantic/Canary", label: "Atlantic/Canary" },
    { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde" },
    { value: "Australia/Adelaide", label: "Australia/Adelaide" },
    { value: "Australia/Brisbane", label: "Australia/Brisbane" },
    { value: "Australia/Canberra", label: "Australia/Canberra" },
    { value: "Australia/Darwin", label: "Australia/Darwin" },
    { value: "Australia/Hobart", label: "Australia/Hobart" },
    { value: "Australia/Perth", label: "Australia/Perth" },
    { value: "Australia/Sydney", label: "Australia/Sydney" },
    { value: "Canada/Atlantic", label: "Canada/Atlantic" },
    { value: "Canada/Newfoundland", label: "Canada/Newfoundland" },
    { value: "Canada/Saskatchewan", label: "Canada/Saskatchewan" },
    { value: "Etc/GMT+12", label: "Etc/GMT+12" },
    { value: "Etc/GMT+2", label: "Etc/GMT+2" },
    { value: "Etc/Greenwich", label: "Etc/Greenwich" },
    { value: "Europe/Amsterdam", label: "Europe/Amsterdam" },
    { value: "Europe/Athens", label: "Europe/Athens" },
    { value: "Europe/Belgrade", label: "Europe/Belgrade" },
    { value: "Europe/Brussels", label: "Europe/Brussels" },
    { value: "Europe/Bucharest", label: "Europe/Bucharest" },
    { value: "Europe/Helsinki", label: "Europe/Helsinki" },
    { value: "Europe/London", label: "Europe/London" },
    { value: "Europe/Madrid", label: "Europe/Madrid" },
    { value: "Europe/Moscow", label: "Europe/Moscow" },
    { value: "Europe/Oslo", label: "Europe/Oslo" },
    { value: "Europe/Sarajevo", label: "Europe/Sarajevo" },
    { value: "GMT", label: "GMT" },
    { value: "Pacific/Auckland", label: "Pacific/Auckland" },
    { value: "Pacific/Fiji", label: "Pacific/Fiji" },
    { value: "Pacific/Guam", label: "Pacific/Guam" },
    { value: "Pacific/Honolulu", label: "Pacific/Honolulu" },
    { value: "Pacific/Midway", label: "Pacific/Midway" },
    { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu" },
    { value: "US/Alaska", label: "US/Alaska" },
    { value: "US/Arizona", label: "US/Arizona" },
    { value: "US/Central", label: "US/Central" },
    { value: "US/East-Indiana", label: "US/East-Indiana" },
    { value: "US/Eastern", label: "US/Eastern" },
    { value: "US/Mountain", label: "US/Mountain" },
    { value: "UTC", label: "UTC" },
  ];
  
 export const countries = [
    { value: "AF", label: "Afghanistan" },
    { value: "AX", label: "Aland Islands" },
    { value: "AL", label: "Albania" },
    { value: "DZ", label: "Algeria" },
    { value: "AS", label: "American Samoa" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AI", label: "Anguilla" },
    { value: "AQ", label: "Antarctica" },
    { value: "AG", label: "Antigua and Barbuda" },
    { value: "AR", label: "Argentina" },
    { value: "AM", label: "Armenia" },
    { value: "AW", label: "Aruba" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "AZ", label: "Azerbaijan" },
    { value: "BS", label: "Bahamas" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesh" },
    { value: "BB", label: "Barbados" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgium" },
    { value: "BZ", label: "Belize" },
    { value: "BJ", label: "Benin" },
    { value: "BM", label: "Bermuda" },
    { value: "BT", label: "Bhutan" },
    { value: "BO", label: "Bolivia" },
    { value: "BA", label: "Bosnia and Herzegovina" },
    { value: "BW", label: "Botswana" },
    { value: "BV", label: "Bouvet Island" },
    { value: "BR", label: "Brazil" },
    { value: "IO", label: "British Indian Ocean Territory" },
    { value: "BN", label: "Brunei Darussalam" },
    { value: "BG", label: "Bulgaria" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "KH", label: "Cambodia" },
    { value: "CM", label: "Cameroon" },
    { value: "CA", label: "Canada" },
    { value: "CV", label: "Cape Verde" },
    { value: "KY", label: "Cayman Islands" },
    { value: "CF", label: "Central African Republic" },
    { value: "TD", label: "Chad" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CX", label: "Christmas Island" },
    { value: "CC", label: "Cocos (Keeling) Islands" },
    { value: "CO", label: "Colombia" },
    { value: "KM", label: "Comoros" },
    { value: "CG", label: "Congo" },
    { value: "CD", label: "Congo (The Democratic Republic of the)" },
    { value: "CK", label: "Cook Islands" },
    { value: "CR", label: "Costa Rica" },
    { value: "CI", label: "Cote D'Ivoire" },
    { value: "HR", label: "Croatia" },
    { value: "CU", label: "Cuba" },
    { value: "CY", label: "Cyprus" },
    { value: "CZ", label: "Czech Republic" },
    { value: "DK", label: "Denmark" },
    { value: "DJ", label: "Djibouti" },
    { value: "DM", label: "Dominica" },
    { value: "DO", label: "Dominican Republic" },
    { value: "EC", label: "Ecuador" },
    { value: "EG", label: "Egypt" },
    { value: "SV", label: "El Salvador" },
    { value: "GQ", label: "Equatorial Guinea" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estonia" },
    { value: "ET", label: "Ethiopia" },
    { value: "FK", label: "Falkland Islands (Malvinas)" },
    { value: "FO", label: "Faroe Islands" },
    { value: "FJ", label: "Fiji" },
    { value: "FI", label: "Finland" },
    { value: "FR", label: "France" },
    { value: "GF", label: "French Guiana" },
    { value: "PF", label: "French Polynesia" },
    { value: "TF", label: "French Southern Territories" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgia" },
    { value: "DE", label: "Germany" },
    { value: "GH", label: "Ghana" },
    { value: "GI", label: "Gibraltar" },
    { value: "GR", label: "Greece" },
    { value: "GL", label: "Greenland" },
    { value: "GD", label: "Grenada" },
    { value: "GP", label: "Guadeloupe" },
    { value: "GU", label: "Guam" },
    { value: "GT", label: "Guatemala" },
    { value: "GG", label: "Guernsey" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "GY", label: "Guyana" },
    { value: "HT", label: "Haiti" },
    { value: "HM", label: "Heard Island and Mcdonald Islands" },
    { value: "VA", label: "Holy See (Vatican City State)" },
    { value: "HN", label: "Honduras" },
    { value: "HK", label: "Hong Kong" },
    { value: "HU", label: "Hungary" },
    { value: "IS", label: "Iceland" },
    { value: "IN", label: "India" },
    { value: "ID", label: "Indonesia" },
    { value: "IR", label: "Iran (Islamic Republic Of)" },
    { value: "IQ", label: "Iraq" },
    { value: "IE", label: "Ireland" },
    { value: "IM", label: "Isle of Man" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italy" },
    { value: "JM", label: "Jamaica" },
    { value: "JP", label: "Japan" },
    { value: "JE", label: "Jersey" },
    { value: "JO", label: "Jordan" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KI", label: "Kiribati" },
    { value: "KP", label: "Korea (Democratic People's Republic)" },
    { value: "KR", label: "Korea (Republic of)" },
    { value: "XK", label: "Kosovo" },
    { value: "KW", label: "Kuwait" },
    { value: "KG", label: "Kyrgyzstan" },
    { value: "LA", label: "Lao People's Democratic Republic" },
    { value: "LV", label: "Latvia" },
    { value: "LB", label: "Lebanon" },
    { value: "LS", label: "Lesotho" },
    { value: "LR", label: "Liberia" },
    { value: "LY", label: "Libyan Arab Jamahiriya" },
    { value: "LI", label: "Liechtenstein" },
    { value: "LT", label: "Lithuania" },
    { value: "LU", label: "Luxembourg" },
    { value: "MO", label: "Macao" },
    { value: "MK", label: "Macedonia (The Former Yugoslav Republic of)" },
    { value: "MG", label: "Madagascar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "MV", label: "Maldives" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MH", label: "Marshall Islands" },
    { value: "MQ", label: "Martinique" },
    { value: "MR", label: "Mauritania" },
    { value: "MU", label: "Mauritius" },
    { value: "YT", label: "Mayotte" },
    { value: "MX", label: "Mexico" },
    { value: "FM", label: "Micronesia (Federated States of)" },
    { value: "MD", label: "Moldova (Republic of)" },
    { value: "MC", label: "Monaco" },
    { value: "MN", label: "Mongolia" },
    { value: "ME", label: "Montenegro" },
    { value: "MS", label: "Montserrat" },
    { value: "MA", label: "Morocco" },
    { value: "MZ", label: "Mozambique" },
    { value: "MM", label: "Myanmar" },
    { value: "NA", label: "Namibia" },
    { value: "NR", label: "Nauru" },
    { value: "NP", label: "Nepal" },
    { value: "NL", label: "Netherlands" },
    { value: "AN", label: "Netherlands Antilles" },
    { value: "NC", label: "New Caledonia" },
    { value: "NZ", label: "New Zealand" },
    { value: "NI", label: "Nicaragua" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "NU", label: "Niue" },
    { value: "NF", label: "Norfolk Island" },
    { value: "MP", label: "Northern Mariana Islands" },
    { value: "NO", label: "Norway" },
    { value: "OM", label: "Oman" },
    { value: "PK", label: "Pakistan" },
    { value: "PW", label: "Palau" },
    { value: "PS", label: "Palestinian Territory (Occupied)" },
    { value: "PA", label: "Panama" },
    { value: "PG", label: "Papua New Guinea" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PH", label: "Philippines" },
    { value: "PN", label: "Pitcairn" },
    { value: "PL", label: "Poland" },
    { value: "PT", label: "Portugal" },
    { value: "PR", label: "Puerto Rico" },
    { value: "QA", label: "Qatar" },
    { value: "RE", label: "Reunion" },
    { value: "RO", label: "Romania" },
    { value: "RU", label: "Russian Federation" },
    { value: "RW", label: "Rwanda" },
    { value: "SH", label: "Saint Helena" },
    { value: "KN", label: "Saint Kitts and Nevis" },
    { value: "LC", label: "Saint Lucia" },
    { value: "MF", label: "Saint Martin" },
    { value: "PM", label: "Saint Pierre and Miquelon" },
    { value: "VC", label: "Saint Vincent and the Grenadines" },
    { value: "WS", label: "Samoa" },
    { value: "SM", label: "San Marino" },
    { value: "ST", label: "Sao Tome and Principe" },
    { value: "SA", label: "Saudi Arabia" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbia" },
    { value: "SC", label: "Seychelles" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapore" },
    { value: "SX", label: "Sint Maarten" },
    { value: "SK", label: "Slovakia" },
    { value: "SI", label: "Slovenia" },
    { value: "SB", label: "Solomon Islands" },
    { value: "SO", label: "Somalia" },
    { value: "ZA", label: "South Africa" },
    { value: "GS", label: "South Georgia and the South Sandwich Islands" },
    { value: "ES", label: "Spain" },
    { value: "LK", label: "Sri Lanka" },
    { value: "SD", label: "Sudan" },
    { value: "SR", label: "Suriname" },
    { value: "SJ", label: "Svalbard and Jan Mayen" },
    { value: "SZ", label: "Swaziland" },
    { value: "SE", label: "Sweden" },
    { value: "CH", label: "Switzerland" },
    { value: "SY", label: "Syrian Arab Republic" },
    { value: "TW", label: "Taiwan" },
    { value: "TJ", label: "Tajikistan" },
    { value: "TZ", label: "Tanzania (United Republic of)" },
    { value: "TH", label: "Thailand" },
    { value: "TL", label: "Timor-Leste" },
    { value: "TG", label: "Togo" },
    { value: "TK", label: "Tokelau" },
    { value: "TO", label: "Tonga" },
    { value: "TT", label: "Trinidad and Tobago" },
    { value: "TN", label: "Tunisia" },
    { value: "TR", label: "Turkey" },
    { value: "TM", label: "Turkmenistan" },
    { value: "TC", label: "Turks and Caicos Islands" },
    { value: "TV", label: "Tuvalu" },
    { value: "UG", label: "Uganda" },
    { value: "GB", label: "UK" },
    { value: "UA", label: "Ukraine" },
    { value: "AE", label: "United Arab Emirates" },
    { value: "US", label: "United States" },
    { value: "UM", label: "United States Minor Outlying Islands" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Uzbekistan" },
    { value: "VU", label: "Vanuatu" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Viet Nam" },
    { value: "VG", label: "Virgin Islands (British)" },
    { value: "VI", label: "Virgin Islands (U.S.)" },
    { value: "WF", label: "Wallis and Futuna" },
    { value: "EH", label: "Western Sahara" },
    { value: "YE", label: "Yemen" },
    { value: "ZM", label: "Zambia" },
    { value: "ZW", label: "Zimbabwe" }
  ];
  